---
output:
  html_document:
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  warning = FALSE
)
library("psych", lib.loc = "~/R/win-library/3.3")
library("zoom", lib.loc = "~/R/win-library/3.3")
library("knitr", lib.loc = "~/R/win-library/3.3")
setwd("C:/Users/Markus/Sync/Bachelor/exst_clasp/Experiments")

```

```{r load data, echo=FALSE, message=FALSE, warning=FALSE}

Statistics <-
  read.csv(
    file = "Statistics.csv",
    header = TRUE,
    sep = ",",
    quote = "\"",
    dec = "."
  )
stat <- Statistics[, -40:-69]
stat <- stat[, -2]

```

##Correlation per Problem with Plots

```{r correlations per problem with plots, echo=FALSE, message=FALSE, warning=FALSE,results='asis'}

for (pro in unique(stat[, 1])) {
  st <- stat[stat$problem == pro,]
  lenst <- sum(!is.na(st[, 1]))
  if (lenst > 10) {
    a <- corr.test(st[, -1], adjust = "none")
    corelationp <- round(a$r, 2)
    cat(sprintf("\n\n### %s\n\n", pro))
    cat("Instanzes: " , lenst)
    print(kable(
      corelationp,
      digits = 3,
      col.names = colnames(corelationp)
    ))
    for (a in 1:length(corelationp[, 1])) {
      for (b in 1:length(corelationp[, 1])) {
        if (!is.na(corelationp[a, b])) {
          if (!is.na(max(st[, a+1])) &&
                !is.na(max(st[, b+1])) && (a < b) &&
              (abs(corelationp[a, b]) > 0.6)) {
            cat(sprintf(
              "\n\n#### Problem: %s Statistic: %s vs. %s Correlation: %s\n\n",
              pro,
              colnames(st)[a+1],
              colnames(st)[b+1],
              corelationp[a, b]
            ))
            print(plot(
              x = st[, a+1],
              y = st[, b+1],
              xlab = colnames(st)[a+1],
              ylab = colnames(st)[b+1],
              xlim = c(min(st[, a+1]), max(st[, a+1])),
              ylim = c(min(st[, b+1]), max(st[, b+1])),
              pch = "x"
            ))
          }
        }
      }
    }
  }
}

```
