---
output:
  html_document:
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  warning = FALSE
)
library("psych", lib.loc = "~/R/win-library/3.3")
library("zoom", lib.loc = "~/R/win-library/3.3")
library("knitr", lib.loc = "~/R/win-library/3.3")
setwd("C:/Users/Markus/Sync/Bachelor/exst_clasp/Experiments")

```

```{r load data, echo=FALSE, message=FALSE, warning=FALSE}

Statistics <-
  read.csv(
    file = "Statistics.csv",
    header = TRUE,
    sep = ",",
    quote = "\"",
    dec = "."
  )
stat <- Statistics[, -40:-69]
stat <- stat[, -2]

```

```{r correlations, echo=FALSE, message=FALSE, warning=FALSE}

a <- corr.test(stat[, -1], adjust = "none")
corelation <- round(a$r, 2)
list_cor = matrix(nrow = 0, ncol = 3)
for (a in 1:length(corelation[, 1])) {
  for (b in 1:length(corelation[, 1])) {
    if (!is.na(corelation[a, b])) {
      if ((a < b)) {
        list_cor <-
          rbind(list_cor, c(
            row.names(corelation)[a],
            colnames(corelation)[b],
            corelation[a, b]
          ))
      }
    }
  }
}

```

#All Plots

```{r Raw Plots with correlation, echo=FALSE, message=FALSE, warning=FALSE}

borders <-
  matrix(c(c(1, 0.7, -0.7, -1),
    c(0.7, 0.5, -0.5, -0.7),
    c(0.5, 0.3, -0.3, -0.5),
    c(0.3, 0, 0, -0.3)), nrow=4,ncol=4)
l <- length(colnames(stat)) - 1
for(i in 1:4) {
  bord <- borders[, i]
  for (a in 1:l) {
    for (b in 1:l) {
      if (!is.na(corelation[a, b])) {
        if (a < b) {
          if ((corelation[a, b] <= bord[1] && corelation[a, b] >= bord[2]) ||
              (corelation[a, b] <= bord[3] &&
               corelation[a, b] >= bord[4])) {
            print(c(
              colnames(corelation)[a],
              colnames(corelation)[b],
              corelation[a, b]
            ))
            num <- 0
            cal <- 0
            for (pro in unique(stat[, 1])) {
              num <- num + 1
              st <- stat[stat$problem == pro,]
              st <- st[, -1]
              if ((sum(!is.na(st[, a])) > 5) &&
                  (sum(!is.na(st[, b])) > 5)) {
                if (cal > 0) {
                  points(
                    x = as.numeric(unlist(st[, b])),
                    y = as.numeric(unlist(st[, a])),
                    pch = num
                  )
                } else {
                  cal <- 1
                  print(
                    plot(
                      x = st[, b],
                      y = st[, a],
                      xlab = colnames(st)[b],
                      ylab = colnames(st)[a],
                      xlim = c(0, ceiling(
                        max(stat[, b + 1], na.rm = TRUE)
                      )),
                      ylim = c(0, ceiling(
                        max(stat[, a + 1], na.rm = TRUE)
                      ))
                    )
                  )
                  
                }
              }
            }
          }
        }
      }
    }
  }
}

```
