---
output:
  html_document:
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  warning = FALSE
)
library("psych", lib.loc = "~/R/win-library/3.3")
library("zoom", lib.loc = "~/R/win-library/3.3")
library("knitr", lib.loc = "~/R/win-library/3.3")
setwd("C:/Users/Markus/Sync/Bachelor/exst_clasp/Experiments")

```

```{r load data, echo=FALSE, message=FALSE, warning=FALSE}

Statistics <-
  read.csv(
    file = "Statistics.csv",
    header = TRUE,
    sep = ",",
    quote = "\"",
    dec = "."
  )
stat <- Statistics[, -40:-69]
stat <- stat[, -2]

```

# Summary

## Overall Summary
```{r Overall Summary, echo=FALSE, message=FALSE, warning=FALSE}

oSummary = matrix(nrow = 0, ncol = 5)

cat("Number Problems: ", length(unique(stat[, 1])), "\n")
cat("Number Instanzes: ", length(stat[, 1]), "\n")
for (col in 2:length(colnames(stat))) {
    oSummary <-
      rbind(oSummary, c(
      colnames(stat)[col],
      min(stat[, col], na.rm = TRUE),
      max(stat[, col], na.rm = TRUE),
      mean(stat[, col], na.rm = TRUE),
      median(stat[, col], na.rm = TRUE)
      ))
}
kable(oSummary, digits=3, col.names = c("Statistic","Min","Max","Avg","Median"))

```

## Summary per problem
```{r Summary per problem, echo=FALSE, message=FALSE, warning=FALSE}

su = matrix(nrow = 0, ncol = 6)
overview = matrix(nrow = 0, ncol = 2)

for (pro in unique(stat[, 1])) {
  st <- stat[stat$problem == pro, ]
  overview <-
    rbind(overview, c(pro, length(st[, 1])))
  for (col in 2:length(colnames(stat))) {
    su <-
      rbind(su, c(
        pro,
        colnames(stat)[col],
        min(st[, col], na.rm = TRUE),
        max(st[, col], na.rm = TRUE),
        mean(st[, col], na.rm = TRUE),
        median(st[, col], na.rm = TRUE)
      ))
  }
}
kable(overview, digits=3, col.names = c("Problem","Number of Instances"))
kable(su, digits=3, col.names = c("Problem","Statistic","Min","Max","Mean","Median"))

```

## Summary per problem
```{r Summary per problem2, echo=FALSE, message=FALSE, warning=FALSE}

asdf = matrix(nrow = 0, ncol = (length(unique(stat[, 1]))+2))

for (col in 2:length(colnames(stat))) {
  st <- stat[stat$problem == pro,]
  minrow <- c(colnames(stat)[col], "min")
  maxrow <- c(colnames(stat)[col], "max")
  meanrow <- c(colnames(stat)[col], "mean")
  medianrow <-  c(colnames(stat)[col], "median")
  for (pro in unique(stat[, 1])) {
    st <- stat[stat$problem == pro,]
    minrow <- c(minrow, min(st[, col], na.rm = TRUE))
    maxrow <- c(maxrow, max(st[, col], na.rm = TRUE))
    meanrow <- c(meanrow, mean(st[, col], na.rm = TRUE))
    medianrow <-  c(medianrow, median(st[, col], na.rm = TRUE))
  }
  asdf <-    rbind(asdf, minrow)
  asdf <-    rbind(asdf, maxrow)
  asdf <-    rbind(asdf, meanrow)
  asdf <-    rbind(asdf, medianrow)
}
kable(asdf,
      digits = 3,
      col.names = c("statistic", "type", levels(unique(stat[, 1]))))

```

# Correlations

##All Correlations

```{r correlations, echo=FALSE, message=FALSE, warning=FALSE}

a <- corr.test(stat[, -1], adjust = "none")
corelation <- round(a$r, 2)
list_cor = matrix(nrow = 0, ncol = 3)
for (a in 1:length(corelation[, 1])) {
  for (b in 1:length(corelation[, 1])) {
    if (!is.na(corelation[a, b])) {
      if ((a < b)) {
        list_cor <-
          rbind(list_cor, c(
            row.names(corelation)[a],
            colnames(corelation)[b],
            corelation[a, b]
          ))
      }
    }
  }
}

```

```{r print correlations, echo=FALSE, message=FALSE, warning=FALSE}

kable(
      corelation,
      digits = 3,
      col.names = colnames(corelation)
    )

```

##Correlation per Problem

```{r correlations per problem, echo=FALSE, message=FALSE, warning=FALSE,results='asis'}

for (pro in unique(stat[, 1])) {
  st <- stat[stat$problem == pro,]
  lenst <- sum(!is.na(st[, 1]))
  if (lenst > 10) {
    a <- corr.test(st[, -1], adjust = "none")
    corelationp <- round(a$r, 2)
    cat(sprintf("\n\n### %s\n\n", pro))
    cat("Instanzes: " , lenst)
    print(kable(
      corelationp,
      digits = 3,
      col.names = colnames(corelationp)
    ))
  }
}

```

## overview correlations problem
```{r overview correlations per problem, echo=FALSE, message=FALSE, warning=FALSE,results='asis'}
begin <- TRUE
count <- 2
for (pro in unique(stat[, 1])) {
  st <- stat[stat$problem == pro, ]
  lenst <- sum(!is.na(st[, 1]))
  if (lenst > 10) {
    a <- corr.test(st[,-1], adjust = "none")
    if (begin) {
      correlations <- list(round(a$r, 2))
      problems <- list(pro)
      begin <- FALSE
    } else{
      correlations[[count]] <- round(a$r, 2)
      problems[[count]] <- pro
      count <- count + 1
    }
  }
}

```

```{r overview correlations per problem stat, echo=FALSE, message=FALSE, warning=FALSE,results='asis'}

len <- length(colnames(correlations[[1]]))
corrmatrix <- matrix(nrow=len^2,ncol=6)
begin <- TRUE
count <- 2
for (stat1 in 1:len) {
  for (stat2 in 1:len) {
    for (prob in 1:length(problems)) {
      if (begin) {
        cors <- c(correlations[[prob]][stat1, stat2])
      } else{
        cors <- c(cors, correlations[[prob]][stat1, stat2])
      }
    }
    corrmatrix[stat1 * (len-1) + stat2, 1] <- colnames(correlations[[1]])[stat1]
    corrmatrix[stat1 * (len-1) + stat2, 2] <- colnames(correlations[[1]])[stat2]
    corrmatrix[stat1 * (len-1) + stat2, 3] <- min(cors, na.rm = TRUE)
    corrmatrix[stat1 * (len-1) + stat2, 4] <- max(cors, na.rm = TRUE)
    corrmatrix[stat1 * (len-1) + stat2, 5] <- mean(cors, na.rm = TRUE)
    corrmatrix[stat1 * (len-1) + stat2, 6] <- median(cors, na.rm = TRUE)
  }
}

kable(corrmatrix)
```

